version: '2'

services:
  app:
    image: local-web-dashboard
    user: node
    working_dir: /home/node/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /var/share/backgrounds:/home/node/app/public/images/backgrounds
    ports:
      - "4000:4000"
    command: node nodejs/index.js